import type { Brand, Category, Product, SkinType, SkinConcern } from "@/types/product";
import type {
  Order,
  OrderItem,
  Payment,
  Delivery,
  OrderStatus,
  PaymentStatus,
  DeliveryStatus,
} from "@/types/order";
import type { Customer } from "@/types/customer";

export const SKIN_TYPES: SkinType[] = [
  "Oily",
  "Dry",
  "Sensitive",
  "Combination",
  "Normal",
];

export const SKIN_CONCERNS: SkinConcern[] = [
  "Acne",
  "Dark Spots",
  "Redness",
  "Dull Skin",
  "Large Pores",
  "Dryness",
  "Oil Control",
  "Sun Protection",
  "Hydration",
  "Brightening",
];

export const ORDER_STATUSES: OrderStatus[] = [
  "New Order",
  "Waiting Payment",
  "Paid",
  "Preparing",
  "Packing",
  "Delivering",
  "Completed",
  "Cancelled",
];

export const PAYMENT_STATUSES: PaymentStatus[] = [
  "Payment Pending",
  "Payment Submitted",
  "Payment Successful",
  "Payment Failed",
  "Payment Expired",
  "Refunded",
];

export const DELIVERY_STATUSES: DeliveryStatus[] = [
  "Order Created",
  "Payment Successful",
  "Preparing",
  "Packing",
  "Ready for Delivery",
  "Delivering",
  "Completed",
  "Cancelled",
];

export const MOCK_CATEGORIES: Category[] = [
  { id: "c1", name: "Cleanser", slug: "cleanser" },
  { id: "c2", name: "Toner", slug: "toner" },
  { id: "c3", name: "Serum", slug: "serum" },
  { id: "c4", name: "Moisturizer", slug: "moisturizer" },
  { id: "c5", name: "Sunscreen", slug: "sunscreen" },
  { id: "c6", name: "Acne Treatment", slug: "acne-treatment" },
  { id: "c7", name: "Mask", slug: "mask" },
  { id: "c8", name: "Makeup", slug: "makeup" },
  { id: "c9", name: "Skincare Set", slug: "skincare-set" },
  { id: "c10", name: "Hair Care", slug: "hair-care" },
  { id: "c11", name: "Fragrance", slug: "fragrance" },
  { id: "c12", name: "Body Care", slug: "body-care" },
  { id: "c13", name: "Lip Care", slug: "lip-care" },
  { id: "c14", name: "Beauty Tool", slug: "beauty-tool" },
];

export const MOCK_BRANDS: Brand[] = [
  { id: "b1", name: "Anua", slug: "anua" },
  { id: "b2", name: "COSRX", slug: "cosrx" },
  { id: "b3", name: "Beauty of Joseon", slug: "beauty-of-joseon" },
  { id: "b4", name: "Skin1004", slug: "skin1004" },
  { id: "b5", name: "CeraVe", slug: "cerave" },
  { id: "b6", name: "The Ordinary", slug: "the-ordinary" },
  { id: "b7", name: "Some By Mi", slug: "some-by-mi" },
  { id: "b8", name: "La Roche-Posay", slug: "la-roche-posay" },
  { id: "b9", name: "Laneige", slug: "laneige" },
  { id: "b10", name: "Rom&nd", slug: "romand" },
  { id: "b11", name: "Dr. Jart+", slug: "dr-jart" },
  { id: "b12", name: "Innisfree", slug: "innisfree" },
  { id: "b13", name: "Kundal", slug: "kundal" },
  { id: "b14", name: "Maison Margiela", slug: "maison-margiela" },
  { id: "b15", name: "Torriden", slug: "torriden" },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Anua Heartleaf 77% Soothing Toner",
    brand_id: "b1",
    origin: "Korea",
    category_id: "c2",
    price: 18,
    stock: 10,
    description:
      "Calming toner with 77% heartleaf extract. Soothes redness and keeps skin balanced throughout the day.",
    main_benefit: "Calming, hydration, redness relief",
    how_to_use:
      "Apply after cleansing using a cotton pad or hands. Pat gently into skin.",
    ingredients: "Houttuynia Cordata Extract 77%, Panthenol, Niacinamide",
    skin_types: ["Sensitive", "Oily", "Combination"],
    skin_concerns: ["Acne", "Redness", "Hydration"],
    ai_tags: ["calming", "sensitive skin", "acne redness", "heartleaf"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p2",
    name: "COSRX Low pH Good Morning Gel Cleanser",
    brand_id: "b2",
    origin: "Korea",
    category_id: "c1",
    price: 12,
    original_price: 15,
    stock: 8,
    description:
      "Low pH gel cleanser with tea tree oil. Gently removes impurities without stripping the skin barrier.",
    main_benefit: "Gentle cleansing for acne-prone skin",
    how_to_use: "Wet face, massage cleanser onto skin, rinse with lukewarm water.",
    ingredients: "Tea Tree Oil, BHA, Allantoin",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Acne", "Oil Control"],
    ai_tags: ["acne", "cleanser", "oil control", "low pH"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p3",
    name: "Beauty of Joseon Relief Sun SPF50+",
    brand_id: "b3",
    origin: "Korea",
    category_id: "c5",
    price: 17,
    stock: 15,
    description:
      "Lightweight sunscreen with rice and probiotic extracts. Provides broad-spectrum UV protection with a soft finish.",
    main_benefit: "Daily UV protection, gentle formula",
    how_to_use: "Apply as the last skincare step every morning. Reapply every 2 hours.",
    ingredients: "Rice Extract, Probiotic, Zinc Oxide",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Sun Protection", "Brightening"],
    ai_tags: ["sunscreen", "spf50", "brightening", "lightweight"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p4",
    name: "Skin1004 Madagascar Centella Ampoule",
    brand_id: "b4",
    origin: "Korea",
    category_id: "c3",
    price: 22,
    stock: 6,
    description:
      "Pure centella asiatica ampoule for sensitive and irritated skin. Calms, repairs, and strengthens the skin barrier.",
    main_benefit: "Soothing and barrier repair",
    how_to_use: "Apply 2–3 drops after toner. Pat gently.",
    ingredients: "Centella Asiatica Extract 100%, Madecassoside",
    skin_types: ["Sensitive", "Dry"],
    skin_concerns: ["Redness", "Acne", "Hydration"],
    ai_tags: ["centella", "soothing", "barrier", "sensitive"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p5",
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    brand_id: "b6",
    origin: "USA",
    category_id: "c3",
    price: 8,
    original_price: 11,
    stock: 3,
    description:
      "High-strength vitamin B3 serum that visibly minimizes pores and controls excess oil.",
    main_benefit: "Oil control and blemish reduction",
    how_to_use: "Apply a few drops after cleansing, before heavier products.",
    ingredients: "Niacinamide 10%, Zinc PCA 1%",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Oil Control", "Large Pores", "Acne"],
    ai_tags: ["niacinamide", "oil control", "pores", "blemish"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p6",
    name: "CeraVe Moisturizing Cream",
    brand_id: "b5",
    origin: "USA",
    category_id: "c4",
    price: 16,
    stock: 12,
    description:
      "Rich, non-greasy moisturizer with ceramides and hyaluronic acid. Restores the skin barrier and provides 24-hour hydration.",
    main_benefit: "Long-lasting hydration and barrier restoration",
    how_to_use: "Apply morning and night to face and body.",
    ingredients: "Ceramides NP, AP, EOP, Hyaluronic Acid, Niacinamide",
    skin_types: ["Dry", "Sensitive", "Normal"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["ceramide", "moisturizer", "dry skin", "barrier"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p7",
    name: "Some By Mi AHA BHA PHA 30 Days Miracle Toner",
    brand_id: "b7",
    origin: "Korea",
    category_id: "c2",
    price: 15,
    original_price: 19,
    stock: 7,
    description:
      "Exfoliating toner with AHA, BHA, and PHA acids. Fades dark spots and keeps pores clear with consistent use.",
    main_benefit: "Exfoliation and dark spot reduction",
    how_to_use: "After cleansing, apply with a cotton pad. Use PM only. Wear sunscreen in AM.",
    ingredients: "AHA, BHA, PHA, Tea Tree Extract",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Dark Spots", "Acne", "Large Pores"],
    ai_tags: ["exfoliating", "dark spots", "acne", "aha bha"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p8",
    name: "La Roche-Posay Toleriane Hydrating Gentle Cleanser",
    brand_id: "b8",
    origin: "France",
    category_id: "c1",
    price: 19,
    stock: 9,
    description:
      "Ultra-gentle cleanser for sensitive skin. Removes makeup and impurities while preserving the skin microbiome.",
    main_benefit: "Gentle cleansing for reactive and sensitive skin",
    how_to_use: "Rinse or wipe off. No rinsing required for extra-dry skin.",
    ingredients: "Prebiotic Thermal Water, Ceramides, Glycerin",
    skin_types: ["Sensitive", "Dry", "Normal"],
    skin_concerns: ["Redness", "Dryness"],
    ai_tags: ["sensitive cleanser", "gentle", "redness", "microbiome"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p9",
    name: "Beauty of Joseon Glow Serum: Propolis + Niacinamide",
    brand_id: "b3",
    origin: "Korea",
    category_id: "c3",
    price: 20,
    stock: 11,
    description:
      "Brightening serum with 63% propolis and 2% niacinamide. Improves skin clarity and fades uneven tone.",
    main_benefit: "Brightening and glow improvement",
    how_to_use: "Apply after toner, pat 2–3 drops into skin.",
    ingredients: "Propolis Extract 63%, Niacinamide 2%",
    skin_types: ["Oily", "Dry", "Combination", "Normal", "Sensitive"],
    skin_concerns: ["Brightening", "Dark Spots", "Dull Skin"],
    ai_tags: ["brightening", "propolis", "niacinamide", "glow"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p11",
    name: "Laneige Lip Sleeping Mask — Berry",
    brand_id: "b9",
    origin: "Korea",
    category_id: "c7",
    price: 24,
    stock: 14,
    description:
      "Overnight lip mask infused with Moisture Wrap™ technology and antioxidant-rich berry mix. Wake up with soft, plump lips.",
    main_benefit: "Deep overnight lip hydration",
    how_to_use: "Apply generously as the last step in your evening skincare routine. Leave overnight.",
    ingredients: "Shea Butter, Murumuru Seed Butter, Berry Complex (Vitamin C)",
    skin_types: ["Dry", "Normal", "Sensitive", "Oily", "Combination"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["lip mask", "overnight", "berry", "hydration", "sleeping mask"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p10",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    brand_id: "b2",
    origin: "Korea",
    category_id: "c3",
    price: 25,
    stock: 5,
    description:
      "96% snail secretion filtrate essence that deeply hydrates and repairs damaged skin overnight.",
    main_benefit: "Deep hydration and skin repair",
    how_to_use: "Apply after toner before moisturizer. Pat into face and neck.",
    ingredients: "Snail Secretion Filtrate 96%, Sodium Hyaluronate",
    skin_types: ["Dry", "Sensitive", "Combination"],
    skin_concerns: ["Hydration", "Acne", "Dull Skin"],
    ai_tags: ["snail mucin", "hydration", "repair", "essence"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p12",
    name: "Rom&nd Juicy Lasting Tint — Figfig",
    brand_id: "b10",
    origin: "Korea",
    category_id: "c8",
    price: 11,
    stock: 18,
    description:
      "Glossy lip tint with a syrup-like finish. Adds a soft berry wash that wears comfortably through the day.",
    main_benefit: "Glossy long-wear lip color",
    how_to_use: "Apply one layer for a natural stain or build up for a deeper glossy look.",
    ingredients: "Fruit Extract, Gloss Polymer, Moisturizing Oil",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Hydration"],
    ai_tags: ["lip tint", "makeup", "gloss", "berry", "romand"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p13",
    name: "Rom&nd Better Than Palette — Rosebud Garden",
    brand_id: "b10",
    origin: "Korea",
    category_id: "c8",
    price: 26,
    stock: 9,
    description:
      "Soft rose eye palette with buildable mattes and refined shimmer shades for everyday looks.",
    main_benefit: "Soft wearable eye color",
    how_to_use: "Blend matte shades first, then tap shimmer shades onto the lid or inner corner.",
    ingredients: "Mica, Silica, Squalane, Pearl Powder",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dull Skin", "Brightening"],
    ai_tags: ["eyeshadow", "makeup", "rose", "palette"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p14",
    name: "Dr. Jart+ Cicapair Tiger Grass Color Correcting Treatment",
    brand_id: "b11",
    origin: "Korea",
    category_id: "c4",
    price: 42,
    stock: 6,
    description:
      "Green-to-beige correcting cream that calms visible redness and leaves a polished, even finish.",
    main_benefit: "Redness correction and barrier comfort",
    how_to_use: "Warm a small amount between fingers and press over red areas after moisturizer.",
    ingredients: "Centella Asiatica, Tiger Grass Complex, Zinc Oxide",
    skin_types: ["Sensitive", "Dry", "Normal"],
    skin_concerns: ["Redness", "Sun Protection", "Dryness"],
    ai_tags: ["cicapair", "redness", "color correcting", "sensitive"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p15",
    name: "Torriden Dive-In Low Molecular Hyaluronic Acid Serum",
    brand_id: "b15",
    origin: "Korea",
    category_id: "c3",
    price: 21,
    stock: 16,
    description:
      "Lightweight hyaluronic acid serum that layers easily and floods dehydrated skin with fresh moisture.",
    main_benefit: "Weightless hydration for dehydrated skin",
    how_to_use: "Apply two pumps after toner while skin is slightly damp.",
    ingredients: "5D Hyaluronic Acid Complex, Panthenol, Allantoin",
    skin_types: ["Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Hydration", "Dryness", "Dull Skin"],
    ai_tags: ["hyaluronic acid", "hydration", "dehydrated", "serum"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p16",
    name: "Innisfree Green Tea Seed Hyaluronic Cream",
    brand_id: "b12",
    origin: "Japan",
    category_id: "c4",
    price: 28,
    stock: 13,
    description:
      "Fresh gel-cream moisturizer with green tea and hyaluronic acid for plump, comfortable skin.",
    main_benefit: "Fresh moisture and soft plumpness",
    how_to_use: "Massage onto face and neck morning or night after serum.",
    ingredients: "Green Tea Water, Hyaluronic Acid, Squalane",
    skin_types: ["Dry", "Combination", "Normal"],
    skin_concerns: ["Hydration", "Dull Skin", "Dryness"],
    ai_tags: ["green tea", "cream", "hydrating", "innisfree"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p17",
    name: "Innisfree Super Volcanic Pore Clay Mask",
    brand_id: "b12",
    origin: "Japan",
    category_id: "c7",
    price: 19,
    original_price: 24,
    stock: 7,
    description:
      "Cooling clay mask that absorbs excess oil and refines the look of congested pores.",
    main_benefit: "Oil absorption and pore refinement",
    how_to_use: "Apply to clean dry skin for 10 minutes, then rinse. Use one to two times weekly.",
    ingredients: "Volcanic Cluster, Kaolin, Bentonite, Lactic Acid",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Oil Control", "Large Pores", "Acne"],
    ai_tags: ["clay mask", "pores", "oily skin", "volcanic"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p18",
    name: "Kundal Honey & Macadamia Shampoo — Baby Powder",
    brand_id: "b13",
    origin: "Japan",
    category_id: "c10",
    price: 15,
    stock: 20,
    description:
      "Gentle scented shampoo with honey and macadamia extract for soft, clean-feeling hair.",
    main_benefit: "Soft cleansing with a powdery scent",
    how_to_use: "Massage into wet scalp, lather, and rinse thoroughly.",
    ingredients: "Honey Extract, Macadamia Seed Extract, Plant Surfactants",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["shampoo", "hair", "baby powder", "kundal"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p19",
    name: "Kundal Protein Treatment — White Musk",
    brand_id: "b13",
    origin: "Korea",
    category_id: "c10",
    price: 16,
    original_price: 20,
    stock: 17,
    description:
      "Creamy hair treatment that helps dry lengths feel smoother, softer, and easier to detangle.",
    main_benefit: "Smooth hair and reduced dryness",
    how_to_use: "Apply from mid-lengths to ends after shampoo. Leave for 3 minutes and rinse.",
    ingredients: "Hydrolyzed Protein, Macadamia Oil, Honey Extract",
    skin_types: ["Dry", "Normal", "Combination"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["hair treatment", "protein", "white musk", "smooth"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p20",
    name: "Maison Margiela Replica Lazy Sunday Morning EDT",
    brand_id: "b14",
    origin: "France",
    category_id: "c11",
    price: 85,
    stock: 4,
    description:
      "Clean floral musk fragrance inspired by fresh sheets, soft skin, and quiet morning light.",
    main_benefit: "Fresh clean everyday fragrance",
    how_to_use: "Spray onto pulse points. Avoid rubbing the fragrance after application.",
    ingredients: "Lily of the Valley, Iris, White Musk",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dull Skin"],
    ai_tags: ["fragrance", "clean", "musk", "fresh"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p21",
    name: "Maison Margiela Replica Beach Walk EDT",
    brand_id: "b14",
    origin: "France",
    category_id: "c11",
    price: 85,
    original_price: 98,
    stock: 5,
    description:
      "Solar floral fragrance with creamy coconut and salty skin notes for a warm beach impression.",
    main_benefit: "Warm sunny fragrance",
    how_to_use: "Mist over pulse points and clothing from a safe distance.",
    ingredients: "Bergamot, Coconut Milk, Ylang-Ylang, Musk",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Brightening"],
    ai_tags: ["fragrance", "summer", "coconut", "beach"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p22",
    name: "La Roche-Posay Anthelios Melt-In Milk SPF60",
    brand_id: "b8",
    origin: "France",
    category_id: "c5",
    price: 27,
    stock: 10,
    description:
      "High protection sunscreen for face and body with a comfortable, non-sticky finish.",
    main_benefit: "High UV protection for face and body",
    how_to_use: "Apply generously 15 minutes before sun exposure. Reapply every two hours.",
    ingredients: "Avobenzone, Homosalate, Octisalate, Thermal Water",
    skin_types: ["Dry", "Sensitive", "Normal", "Combination"],
    skin_concerns: ["Sun Protection", "Redness"],
    ai_tags: ["spf", "body sunscreen", "sensitive", "anthelios"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p23",
    name: "CeraVe SA Smoothing Cleanser",
    brand_id: "b5",
    origin: "USA",
    category_id: "c1",
    price: 14,
    original_price: 18,
    stock: 8,
    description:
      "Salicylic acid cleanser for rough texture and blemish-prone skin without a stripped feeling.",
    main_benefit: "Smoother texture and gentle exfoliation",
    how_to_use: "Massage onto wet skin, rinse, and follow with moisturizer.",
    ingredients: "Salicylic Acid, Ceramides, Niacinamide",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Acne", "Large Pores", "Oil Control"],
    ai_tags: ["salicylic acid", "texture", "cleanser", "acne"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p24",
    name: "Anua Peach 70 Niacin Serum",
    brand_id: "b1",
    origin: "Korea",
    category_id: "c3",
    price: 23,
    stock: 12,
    description:
      "Peach extract and niacinamide serum designed to brighten uneven tone and soften dull skin.",
    main_benefit: "Glow and tone-evening support",
    how_to_use: "Apply two to three drops before moisturizer. Use sunscreen in the morning.",
    ingredients: "Peach Extract 70%, Niacinamide, Vitamin B12",
    skin_types: ["Dry", "Combination", "Normal", "Oily"],
    skin_concerns: ["Brightening", "Dull Skin", "Dark Spots"],
    ai_tags: ["peach", "niacinamide", "glow", "serum"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p25",
    name: "Skin1004 Hyalu-Cica Water-Fit Sun Serum SPF50+",
    brand_id: "b4",
    origin: "Korea",
    category_id: "c5",
    price: 18,
    stock: 19,
    description:
      "Serum-like sunscreen with centella and hyaluronic acid for comfortable daily protection.",
    main_benefit: "Hydrating daily SPF with a fresh finish",
    how_to_use: "Apply as the final morning skincare step and reapply throughout the day.",
    ingredients: "Centella Asiatica, Hyaluronic Acid, Chemical UV Filters",
    skin_types: ["Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Sun Protection", "Hydration", "Redness"],
    ai_tags: ["sunscreen", "hyalu-cica", "centella", "lightweight"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p26",
    name: "Beauty of Joseon Ginseng Cleansing Oil",
    brand_id: "b3",
    origin: "Korea",
    category_id: "c1",
    price: 19,
    stock: 9,
    description:
      "Light oil cleanser that melts sunscreen and makeup while leaving skin soft and comfortable.",
    main_benefit: "Gentle makeup and sunscreen removal",
    how_to_use: "Massage onto dry skin, emulsify with water, then rinse.",
    ingredients: "Soybean Oil, Ginseng Seed Oil, Olive Oil",
    skin_types: ["Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dryness", "Dull Skin"],
    ai_tags: ["cleansing oil", "ginseng", "makeup remover", "double cleanse"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p27",
    name: "The Ordinary Glycolic Acid 7% Exfoliating Toner",
    brand_id: "b6",
    origin: "USA",
    category_id: "c2",
    price: 13,
    original_price: 16,
    stock: 6,
    description:
      "Exfoliating toner for uneven texture and dull tone. Also popular for body roughness routines.",
    main_benefit: "Surface exfoliation and glow",
    how_to_use: "Use at night two to three times weekly. Avoid eye area and use sunscreen.",
    ingredients: "Glycolic Acid 7%, Tasmanian Pepperberry, Aloe Vera",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Dull Skin", "Large Pores", "Dark Spots"],
    ai_tags: ["glycolic acid", "exfoliation", "toner", "texture"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
  },
  {
    id: "p28",
    name: "Laneige Water Sleeping Mask",
    brand_id: "b9",
    origin: "Korea",
    category_id: "c7",
    price: 32,
    stock: 8,
    description:
      "Cooling overnight mask that helps tired skin look rested, hydrated, and luminous by morning.",
    main_benefit: "Overnight hydration and rested glow",
    how_to_use: "Apply as the last evening step two to three times weekly.",
    ingredients: "Hydro Ionized Mineral Water, Squalane, Probiotic Complex",
    skin_types: ["Dry", "Combination", "Normal"],
    skin_concerns: ["Hydration", "Dull Skin", "Dryness"],
    ai_tags: ["sleeping mask", "overnight", "hydration", "laneige"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p29",
    name: "Dr. Jart+ Ceramidin Skin Barrier Serum Toner",
    brand_id: "b11",
    origin: "Korea",
    category_id: "c2",
    price: 39,
    stock: 5,
    description:
      "Milky toner-serum that wraps dry, stressed skin in ceramide-rich comfort.",
    main_benefit: "Barrier support and long-lasting comfort",
    how_to_use: "Apply after cleansing with hands. Layer twice for extra dryness.",
    ingredients: "Ceramide NP, Panthenol, Glycerin",
    skin_types: ["Dry", "Sensitive", "Normal"],
    skin_concerns: ["Dryness", "Redness", "Hydration"],
    ai_tags: ["ceramide", "barrier", "milky toner", "dry skin"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p30",
    name: "Some By Mi Retinol Intense Reactivating Serum",
    brand_id: "b7",
    origin: "Korea",
    category_id: "c3",
    price: 24,
    original_price: 30,
    stock: 4,
    description:
      "Beginner-friendly retinol serum for texture, pores, and early firmness support.",
    main_benefit: "Texture refinement and firmness support",
    how_to_use: "Use at night two times weekly at first. Avoid mixing with strong acids.",
    ingredients: "Retinol, Retinal, Bakuchiol, Panthenol",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Large Pores", "Dull Skin", "Acne"],
    ai_tags: ["retinol", "texture", "pores", "anti-aging"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p31",
    name: "Lumière Soft Cloud Body Cream",
    brand_id: "b15",
    origin: "Korea",
    category_id: "c12",
    price: 18,
    stock: 21,
    description:
      "Mock exclusive body cream with a whipped texture, soft citrus-musk scent, and comfortable hydration.",
    main_benefit: "Soft body hydration without heaviness",
    how_to_use: "Massage onto clean body skin after showering.",
    ingredients: "Shea Butter, Glycerin, Citrus Peel Extract, Musk Accord",
    skin_types: ["Dry", "Sensitive", "Normal"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["body cream", "hydration", "soft skin", "body care"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },
  {
    id: "p32",
    name: "Lumière Daily Glow Skincare Set",
    brand_id: "b1",
    origin: "Japan",
    category_id: "c9",
    price: 58,
    stock: 7,
    description:
      "Routine set with toner, serum, and SPF picks for a simple brightening morning ritual.",
    main_benefit: "Complete easy glow routine",
    how_to_use: "Use the included toner, serum, and sunscreen in that order every morning.",
    ingredients: "Heartleaf Toner, Peach Niacin Serum, Daily SPF",
    skin_types: ["Oily", "Combination", "Normal", "Sensitive"],
    skin_concerns: ["Brightening", "Hydration", "Sun Protection"],
    ai_tags: ["set", "routine", "morning", "glow", "starter kit"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
  },

  // ── MAKEUP — c8 ──────────────────────────────────────────────────────────────

  {
    id: "p33",
    name: "Innisfree No Sebum Mineral Powder",
    brand_id: "b12",
    origin: "Korea",
    category_id: "c8",
    price: 13,
    original_price: 18,
    stock: 22,
    slug: "innisfree-no-sebum-mineral-powder",
    description: "Translucent setting powder with volcanic ash. Controls shine all day for a matte, poreless finish.",
    main_benefit: "Oil control and matte finish",
    how_to_use: "Press lightly over foundation or bare skin. Reapply midday as needed.",
    ingredients: "Volcanic Ash, Mica, Silica, Zinc Stearate",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Oil Control", "Large Pores"],
    ai_tags: ["setting powder", "matte", "oil control", "innisfree"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 1840,
  },
  {
    id: "p34",
    name: "Laneige Neo Cushion — Matte",
    brand_id: "b9",
    origin: "Thailand",
    category_id: "c8",
    price: 38,
    stock: 9,
    slug: "laneige-neo-cushion-matte",
    description: "Full-coverage cushion foundation with a transfer-proof satin finish. Blurs pores and lasts 24 hours.",
    main_benefit: "Full coverage with matte finish",
    how_to_use: "Dab the puff into the cushion and press gently onto the face.",
    ingredients: "Niacinamide, Green Tea Seed Extract, SPF 42 PA+++",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Large Pores", "Oil Control", "Dull Skin"],
    ai_tags: ["cushion", "foundation", "matte", "full coverage"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 2210,
  },
  {
    id: "p35",
    name: "Rom&nd Better Than Concealer",
    brand_id: "b10",
    origin: "Thailand",
    category_id: "c8",
    price: 18,
    stock: 14,
    slug: "romand-better-than-concealer",
    description: "Smooth buildable concealer that covers dark circles and blemishes without creasing.",
    main_benefit: "Lightweight coverage and no-crease formula",
    how_to_use: "Apply with fingertip or brush. Blend outwards. Set with powder for long wear.",
    ingredients: "Jojoba Seed Oil, Hyaluronic Acid, Titanium Dioxide",
    skin_types: ["Dry", "Combination", "Normal", "Oily", "Sensitive"],
    skin_concerns: ["Dull Skin", "Dark Spots"],
    ai_tags: ["concealer", "coverage", "dark circles", "romand"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.4,
    review_count: 780,
  },
  {
    id: "p36",
    name: "Dr. Jart+ Every Sun Day Tone-Up SPF50+",
    brand_id: "b11",
    origin: "Thailand",
    category_id: "c5",
    price: 22,
    original_price: 28,
    stock: 11,
    slug: "dr-jart-every-sun-day-tone-up",
    description: "Tinted SPF that evens skin tone with a soft lavender-white blur effect and SPF50+ protection.",
    main_benefit: "UV protection + instant tone-up",
    how_to_use: "Apply generously as the last morning step. No primer needed.",
    ingredients: "Centella Asiatica, Adenosine, UV Filters SPF50+ PA++++",
    skin_types: ["Dry", "Sensitive", "Normal", "Combination"],
    skin_concerns: ["Sun Protection", "Dull Skin", "Brightening"],
    ai_tags: ["tinted sunscreen", "tone-up", "spf50", "dr jart"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 1120,
  },
  {
    id: "p37",
    name: "Rom&nd Juicy Lasting Tint — Plumping Grape",
    brand_id: "b10",
    origin: "Cambodia",
    category_id: "c8",
    price: 11,
    original_price: 14,
    stock: 26,
    slug: "romand-juicy-lasting-tint-plumping-grape",
    description: "A rich plum-wine tint with a glossy finish and all-day moisture. Iconic K-beauty lip signature.",
    main_benefit: "Long-wear glossy lip color",
    how_to_use: "Apply one coat for a wash of color or layer for a bolder look.",
    ingredients: "Fruit Extract, Gloss Polymer, Jojoba Oil",
    skin_types: ["Dry", "Normal", "Oily", "Combination", "Sensitive"],
    skin_concerns: ["Hydration"],
    ai_tags: ["lip tint", "gloss", "grape", "k-beauty makeup"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 3240,
  },
  {
    id: "p38",
    name: "Beauty of Joseon Revive Eye Serum",
    brand_id: "b3",
    origin: "Cambodia",
    category_id: "c3",
    price: 23,
    stock: 8,
    slug: "beauty-of-joseon-revive-eye-serum",
    description: "Lightweight eye serum with ginseng and retinal for smoothing fine lines and brightening the under-eye.",
    main_benefit: "Fine line reduction and under-eye brightening",
    how_to_use: "Dab gently around the orbital bone using the ring finger. AM and PM.",
    ingredients: "Ginseng Root Extract, Retinal, Niacinamide, Adenosine",
    skin_types: ["Dry", "Combination", "Normal", "Sensitive"],
    skin_concerns: ["Dark Spots", "Dull Skin", "Brightening"],
    ai_tags: ["eye serum", "ginseng", "anti-aging", "brightening"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 960,
  },

  // ── LIP CARE — c13 ───────────────────────────────────────────────────────────

  {
    id: "p39",
    name: "Laneige Lip Glowy Balm — Berry",
    brand_id: "b9",
    origin: "Cambodia",
    category_id: "c13",
    price: 16,
    original_price: 22,
    stock: 30,
    slug: "laneige-lip-glowy-balm-berry",
    description: "Sheer tinted lip balm with a mirror-shine finish. Hydrates, plumps, and adds a berry flush all day.",
    main_benefit: "Sheer gloss with deep lip hydration",
    how_to_use: "Swipe on for shine, layer for more color. Wear alone or over any lip product.",
    ingredients: "Shea Butter, Vitamin C, Berry Complex",
    skin_types: ["Dry", "Normal", "Oily", "Combination", "Sensitive"],
    skin_concerns: ["Hydration", "Dryness"],
    ai_tags: ["lip balm", "tinted", "berry", "gloss", "hydration"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.9,
    review_count: 5620,
  },
  {
    id: "p40",
    name: "Laneige Lip Sleeping Mask — Vanilla Cookie",
    brand_id: "b9",
    origin: "Korea",
    category_id: "c13",
    price: 22,
    stock: 16,
    slug: "laneige-lip-sleeping-mask-vanilla-cookie",
    description: "Creamy overnight lip mask in a warm vanilla-cookie scent. Repairs dry, chapped lips while you sleep.",
    main_benefit: "Overnight lip repair and plumping",
    how_to_use: "Apply as the last evening step. Leave on overnight and rinse in the morning.",
    ingredients: "Shea Butter, Murumuru Butter, Vanilla Bean Extract",
    skin_types: ["Dry", "Normal", "Sensitive", "Oily", "Combination"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["lip mask", "overnight", "vanilla", "sleeping mask"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 3980,
  },
  {
    id: "p41",
    name: "Innisfree My Lip Balm Caring — Honey",
    brand_id: "b12",
    origin: "Korea",
    category_id: "c13",
    price: 8,
    stock: 40,
    slug: "innisfree-my-lip-balm-caring-honey",
    description: "Lightweight everyday lip balm with honey extract and vitamin E for comfortable, smooth lips.",
    main_benefit: "Light daily lip moisture",
    how_to_use: "Apply as needed throughout the day.",
    ingredients: "Honey Extract, Vitamin E, Beeswax, Shea Butter",
    skin_types: ["Dry", "Normal", "Oily", "Combination", "Sensitive"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["lip balm", "honey", "everyday", "hydration"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.3,
    review_count: 680,
  },
  {
    id: "p42",
    name: "Beauty of Joseon Apricot Blossom Lip Butter",
    brand_id: "b3",
    origin: "Korea",
    category_id: "c13",
    price: 12,
    stock: 18,
    slug: "beauty-of-joseon-apricot-blossom-lip-butter",
    description: "Rich yet non-greasy lip butter with apricot kernel oil and Korean herbal extracts for soft, smooth lips.",
    main_benefit: "Nourishing lip care with a clean herbal finish",
    how_to_use: "Apply generously before bed or anytime lips feel dry.",
    ingredients: "Apricot Kernel Oil, Hwanggi Root Extract, Beeswax, Shea Butter",
    skin_types: ["Dry", "Normal", "Sensitive", "Oily", "Combination"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["lip butter", "apricot", "herbal", "k-beauty lips"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 440,
  },
  {
    id: "p43",
    name: "COSRX Advanced Snail Mucin Lip Mask",
    brand_id: "b2",
    origin: "Japan",
    category_id: "c13",
    price: 16,
    stock: 12,
    slug: "cosrx-advanced-snail-mucin-lip-mask",
    description: "Gel lip mask with 92% snail secretion filtrate that repairs dry, flaky lips overnight.",
    main_benefit: "Repair and deep hydration for chapped lips",
    how_to_use: "Apply a thick layer before sleep. Rinse or gently wipe away in the morning.",
    ingredients: "Snail Secretion Filtrate 92%, Hyaluronic Acid, Allantoin",
    skin_types: ["Dry", "Normal", "Sensitive", "Oily", "Combination"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["snail mucin", "lip mask", "repair", "overnight lips"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 590,
  },
  {
    id: "p44",
    name: "Rom&nd Zero Velvet Tint — Fallen Rose",
    brand_id: "b10",
    origin: "Japan",
    category_id: "c13",
    price: 15,
    stock: 20,
    slug: "romand-zero-velvet-tint-fallen-rose",
    description: "Ultra-matte velvet lip tint with zero weight. Deep dusty rose shade that wears for hours without drying.",
    main_benefit: "Long-wear matte lip color",
    how_to_use: "Apply from the center of lips outward. Allow to set for one minute.",
    ingredients: "Jojoba Oil, Tocopherol, Mica, Dimethicone",
    skin_types: ["Dry", "Normal", "Oily", "Combination", "Sensitive"],
    skin_concerns: ["Hydration"],
    ai_tags: ["lip tint", "matte", "velvet", "rose"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 2100,
  },
  {
    id: "p45",
    name: "Some By Mi Truecica Lip Butter",
    brand_id: "b7",
    origin: "Japan",
    category_id: "c13",
    price: 11,
    original_price: 14,
    stock: 25,
    slug: "some-by-mi-truecica-lip-butter",
    description: "Centella-infused lip butter that soothes sensitive or irritated lips while sealing in moisture.",
    main_benefit: "Soothing and moisturizing for reactive lips",
    how_to_use: "Apply morning and night. Perfect under lip color or alone for bare-lip days.",
    ingredients: "Centella Asiatica, Truecica Complex, Shea Butter, Hyaluronic Acid",
    skin_types: ["Dry", "Sensitive", "Normal"],
    skin_concerns: ["Redness", "Dryness", "Hydration"],
    ai_tags: ["lip butter", "centella", "soothing", "sensitive lips"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.4,
    review_count: 510,
  },
  {
    id: "p46",
    name: "Innisfree Virgin Berry Plump Lip Serum",
    brand_id: "b12",
    origin: "Thailand",
    category_id: "c13",
    price: 19,
    stock: 14,
    slug: "innisfree-virgin-berry-plump-lip-serum",
    description: "Berry-powered lip serum that visibly plumps and smooths lip lines for a fuller, juicier look.",
    main_benefit: "Lip plumping and line reduction",
    how_to_use: "Pat a small amount onto lips before lipstick or gloss. Or wear alone.",
    ingredients: "Virgin Berry Complex, Peptides, Hyaluronic Acid",
    skin_types: ["Dry", "Normal", "Oily", "Combination", "Sensitive"],
    skin_concerns: ["Hydration", "Dryness"],
    ai_tags: ["lip serum", "plumping", "berry", "anti-aging lips"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.3,
    review_count: 350,
  },

  // ── HAIR CARE — c10 ──────────────────────────────────────────────────────────

  {
    id: "p47",
    name: "Kundal Honey & Macadamia Conditioner — Cotton Breeze",
    brand_id: "b13",
    origin: "Cambodia",
    category_id: "c10",
    price: 15,
    stock: 22,
    slug: "kundal-honey-conditioner-cotton-breeze",
    description: "Creamy conditioner with honey and macadamia that detangles, softens, and leaves hair smelling fresh.",
    main_benefit: "Soft detangling and light scent",
    how_to_use: "After shampooing, apply from mid-lengths to ends. Leave for 2 minutes and rinse.",
    ingredients: "Honey Extract, Macadamia Seed Oil, Panthenol, Keratin",
    skin_types: ["Dry", "Normal", "Combination"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["conditioner", "hair", "honey", "cotton breeze", "kundal"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 1350,
  },
  {
    id: "p48",
    name: "Kundal Deep Damage Treatment Mask",
    brand_id: "b13",
    origin: "Korea",
    category_id: "c10",
    price: 18,
    original_price: 22,
    stock: 15,
    slug: "kundal-deep-damage-treatment-mask",
    description: "Intensive weekly hair mask for chemically treated or heat-damaged hair. Restores elasticity and shine.",
    main_benefit: "Repairs and restores damaged hair",
    how_to_use: "Apply to clean damp hair, leave for 10 minutes, then rinse thoroughly.",
    ingredients: "Honey Extract, Amino Acids, Macadamia Oil, Argan Oil",
    skin_types: ["Dry", "Combination", "Normal"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["hair mask", "damaged hair", "treatment", "kundal"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 820,
  },
  {
    id: "p49",
    name: "Kundal Argan Oil Hair Serum",
    brand_id: "b13",
    origin: "Korea",
    category_id: "c10",
    price: 16,
    stock: 18,
    slug: "kundal-argan-oil-hair-serum",
    description: "Lightweight argan oil serum that tames frizz, adds mirror shine, and protects from heat up to 230°C.",
    main_benefit: "Frizz control and shine booster",
    how_to_use: "Apply 2–3 drops to damp or dry hair. Focus on mid-lengths to ends.",
    ingredients: "Argan Oil, Keratin, Heat-Protection Polymer",
    skin_types: ["Dry", "Normal", "Combination"],
    skin_concerns: ["Dryness"],
    ai_tags: ["hair serum", "argan oil", "frizz", "shine", "heat protection"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 1680,
  },
  {
    id: "p50",
    name: "Kundal Scalp Scaling Shampoo",
    brand_id: "b13",
    origin: "Korea",
    category_id: "c10",
    price: 18,
    stock: 13,
    slug: "kundal-scalp-scaling-shampoo",
    description: "Gentle scalp-exfoliating shampoo that removes buildup and dandruff while strengthening roots.",
    main_benefit: "Scalp cleanse and dandruff control",
    how_to_use: "Massage into wet scalp for 60 seconds, focusing on the roots. Rinse thoroughly.",
    ingredients: "Salicylic Acid 0.5%, Piroctone Olamine, Honey Extract",
    skin_types: ["Oily", "Normal", "Combination"],
    skin_concerns: ["Oil Control", "Large Pores"],
    ai_tags: ["scalp shampoo", "dandruff", "scalp care", "kundal"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.4,
    review_count: 490,
  },
  {
    id: "p51",
    name: "Innisfree Camellia Essential Hair Serum",
    brand_id: "b12",
    origin: "Korea",
    category_id: "c10",
    price: 22,
    original_price: 28,
    stock: 10,
    slug: "innisfree-camellia-essential-hair-serum",
    description: "Camellia oil serum for dry, coarse hair. Creates a protective coat of moisture for all-day softness.",
    main_benefit: "Deep nourishment and smooth finish",
    how_to_use: "Smooth 2–3 pumps through damp hair before blow-drying.",
    ingredients: "Camellia Sinensis Seed Oil, Ceramide, Panthenol",
    skin_types: ["Dry", "Normal"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["camellia", "hair serum", "nourishing", "innisfree"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 620,
  },
  {
    id: "p52",
    name: "Some By Mi AHA Scalp Clarifying Shampoo",
    brand_id: "b7",
    origin: "Korea",
    category_id: "c10",
    price: 20,
    stock: 12,
    slug: "some-by-mi-aha-scalp-clarifying-shampoo",
    description: "AHA-infused clarifying shampoo that exfoliates the scalp, removes buildup, and promotes a cleaner root environment.",
    main_benefit: "Clarifying shampoo for oily scalp",
    how_to_use: "Work into a lather on wet scalp. Rinse well. Follow with conditioner.",
    ingredients: "AHA Complex, Tea Tree Oil, Aloe Vera, Panthenol",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Oil Control", "Acne"],
    ai_tags: ["aha shampoo", "scalp", "clarifying", "some by mi"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.3,
    review_count: 370,
  },
  {
    id: "p53",
    name: "La Roche-Posay Kerium Anti-Breakage Shampoo",
    brand_id: "b8",
    origin: "France",
    category_id: "c10",
    price: 24,
    stock: 9,
    slug: "la-roche-posay-kerium-anti-breakage-shampoo",
    description: "Strengthening shampoo for brittle, fragile hair. Fortifies each strand with ceramides and thermal water.",
    main_benefit: "Reduces hair breakage and strengthens strands",
    how_to_use: "Apply to wet hair, lather, leave for 2 minutes, then rinse.",
    ingredients: "Ceramides, La Roche-Posay Thermal Water, Pro-Vitamin B5",
    skin_types: ["Dry", "Normal", "Sensitive"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["anti-breakage", "shampoo", "strengthening", "ceramide", "la roche-posay hair"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 910,
  },
  {
    id: "p54",
    name: "The Ordinary Multi-Peptide Serum for Hair Density",
    brand_id: "b6",
    origin: "USA",
    category_id: "c10",
    price: 25,
    original_price: 32,
    stock: 7,
    slug: "the-ordinary-multi-peptide-hair-serum",
    description: "Leave-in scalp serum with 9 hair-supporting technologies. Visibly improves density and reduces shedding.",
    main_benefit: "Thicker, denser-looking hair",
    how_to_use: "Apply to dry or damp scalp. Do not rinse. Style as usual.",
    ingredients: "Caffeine, Redensyl, Procapil, AnaGain, Biotinoyl Tripeptide",
    skin_types: ["Oily", "Dry", "Combination", "Normal"],
    skin_concerns: ["Dryness", "Dull Skin"],
    ai_tags: ["hair density", "peptide", "scalp serum", "hair growth"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.4,
    review_count: 1480,
  },
  {
    id: "p55",
    name: "Innisfree Camellia Essential Hair Mask",
    brand_id: "b12",
    origin: "Korea",
    category_id: "c10",
    price: 24,
    stock: 11,
    slug: "innisfree-camellia-essential-hair-mask",
    description: "Rich weekly hair mask with camellia oil that deeply conditions dry, dull hair and adds luminous shine.",
    main_benefit: "Deep conditioning for dry and dull hair",
    how_to_use: "Apply to damp hair after shampooing. Leave for 5 minutes and rinse well.",
    ingredients: "Camellia Sinensis Seed Oil, Ceramide, Argan Oil, Panthenol",
    skin_types: ["Dry", "Normal"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["hair mask", "camellia", "shine", "deep conditioning"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 540,
  },
  {
    id: "p56",
    name: "Some By Mi Hair Loss Relief Shampoo",
    brand_id: "b7",
    origin: "Korea",
    category_id: "c10",
    price: 18,
    original_price: 23,
    stock: 14,
    slug: "some-by-mi-hair-loss-relief-shampoo",
    description: "Scalp-strengthening shampoo targeting thinning and shedding with biotin, caffeine, and peptides.",
    main_benefit: "Reduces shedding and supports scalp health",
    how_to_use: "Massage well into scalp. Leave for 3 minutes, then rinse thoroughly.",
    ingredients: "Biotin, Caffeine, Keratin Peptide, Niacinamide",
    skin_types: ["Oily", "Dry", "Combination", "Normal"],
    skin_concerns: ["Dull Skin"],
    ai_tags: ["hair loss", "biotin", "scalp", "strengthening shampoo"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.3,
    review_count: 780,
  },
  {
    id: "p57",
    name: "La Roche-Posay Kerium Anti-Dandruff Shampoo",
    brand_id: "b8",
    origin: "France",
    category_id: "c10",
    price: 28,
    stock: 8,
    slug: "la-roche-posay-kerium-anti-dandruff-shampoo",
    description: "Micro-exfoliating dandruff shampoo with LHA acid and selenium. Visible results in 2 weeks.",
    main_benefit: "Persistent dandruff control",
    how_to_use: "Apply to wet scalp, work into lather, leave for 3 minutes, rinse. 2–3x weekly.",
    ingredients: "LHA, Selenium DS, Salicylic Acid, Thermal Water",
    skin_types: ["Oily", "Normal", "Combination"],
    skin_concerns: ["Oil Control"],
    ai_tags: ["dandruff", "scalp shampoo", "micro-exfoliant", "la roche-posay"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 1920,
  },
  {
    id: "p58",
    name: "Kundal Nature Shine Hair Essence",
    brand_id: "b13",
    origin: "Korea",
    category_id: "c10",
    price: 14,
    stock: 20,
    slug: "kundal-nature-shine-hair-essence",
    description: "Finishing hair essence that adds glass-like shine and softness without weighing hair down.",
    main_benefit: "Shine and silkiness without buildup",
    how_to_use: "Apply a few drops to dry or nearly dry hair focusing on mid-lengths.",
    ingredients: "Macadamia Oil, Silk Amino Acid, Argan Oil",
    skin_types: ["Dry", "Normal", "Combination"],
    skin_concerns: ["Dryness"],
    ai_tags: ["hair essence", "shine", "silk", "lightweight"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.4,
    review_count: 390,
  },

  // ── FRAGRANCE — c11 ──────────────────────────────────────────────────────────

  {
    id: "p59",
    name: "Maison Margiela Replica Flower Market EDT",
    brand_id: "b14",
    origin: "France",
    category_id: "c11",
    price: 85,
    stock: 6,
    slug: "maison-margiela-replica-flower-market-edt",
    description: "A vivid floral walk through a sun-dappled market. Rose, peony, and green petals on a warm musky base.",
    main_benefit: "Fresh floral with lasting depth",
    how_to_use: "Spray on pulse points — wrists, neck, behind ears. Let dry naturally.",
    ingredients: "Rose Absolute, Peony, Green Petals, White Musk",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Brightening"],
    ai_tags: ["fragrance", "floral", "rose", "fresh"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 1240,
  },
  {
    id: "p60",
    name: "Maison Margiela Replica Jazz Club EDT",
    brand_id: "b14",
    origin: "France",
    category_id: "c11",
    price: 90,
    stock: 4,
    slug: "maison-margiela-replica-jazz-club-edt",
    description: "Warm, smoky, and seductive — an ode to late nights, leather seating, and rum cocktails.",
    main_benefit: "Rich woody fragrance for evenings",
    how_to_use: "Mist liberally onto clothes and skin. Best worn for cooler months and evenings.",
    ingredients: "Pink Pepper, Rum, Vetiver, Tobacco Leaf, Vanilla",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dull Skin"],
    ai_tags: ["fragrance", "woody", "warm", "evening", "jazz club"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.9,
    review_count: 2340,
  },
  {
    id: "p61",
    name: "Maison Margiela Replica By the Fireplace EDT",
    brand_id: "b14",
    origin: "France",
    category_id: "c11",
    price: 90,
    original_price: 105,
    stock: 3,
    slug: "maison-margiela-replica-by-the-fireplace-edt",
    description: "Warm vanilla chestnut and smoky vetiver. The smell of crackling fire and toasted marshmallow.",
    main_benefit: "Cosy warm fragrance for autumn and winter",
    how_to_use: "Apply to neck, wrists, and chest. Allow to dry. Reapply after 6–8 hours.",
    ingredients: "Clove, Guaiacwood, Chestnut, Vanilla, Vetiver",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dull Skin"],
    ai_tags: ["fragrance", "cosy", "vanilla", "wood", "winter"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.9,
    review_count: 3120,
  },
  {
    id: "p62",
    name: "Maison Margiela Replica Whispers in the Library EDT",
    brand_id: "b14",
    origin: "France",
    category_id: "c11",
    price: 82,
    stock: 5,
    slug: "maison-margiela-replica-whispers-in-the-library-edt",
    description: "A soft, refined scent evoking old books, cedar shelves, and quiet afternoons. Subtle and long-lasting.",
    main_benefit: "Understated refined fragrance for daytime",
    how_to_use: "Spray lightly on pulse points. Perfect as an everyday signature scent.",
    ingredients: "Sandalwood, Cedar, Musk, Heliotrope, White Tea",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dull Skin"],
    ai_tags: ["fragrance", "clean", "cedar", "refined", "daytime"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 980,
  },
  {
    id: "p63",
    name: "Innisfree Jeju Citrus Body & Hair Mist",
    brand_id: "b12",
    origin: "Korea",
    category_id: "c11",
    price: 18,
    stock: 24,
    slug: "innisfree-jeju-citrus-body-hair-mist",
    description: "Light citrus mist made with Jeju tangerine and mandarin. A quick body refresh with a sunny, clean scent.",
    main_benefit: "Refreshing citrus scent for body and hair",
    how_to_use: "Spray onto hair and body from 15cm away after shower or throughout the day.",
    ingredients: "Jeju Tangerine Extract, Mandarin Peel Oil, Glycerin",
    skin_types: ["Oily", "Normal", "Combination", "Dry", "Sensitive"],
    skin_concerns: ["Brightening"],
    ai_tags: ["body mist", "citrus", "jeju", "hair mist", "refresh"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.3,
    review_count: 310,
  },
  {
    id: "p64",
    name: "Laneige Jasmine & Rose Body Mist",
    brand_id: "b9",
    origin: "Thailand",
    category_id: "c11",
    price: 22,
    stock: 18,
    slug: "laneige-jasmine-rose-body-mist",
    description: "Soft romantic floral mist with jasmine and rose petals. Layers perfectly with Laneige body care.",
    main_benefit: "Romantic floral scent that lasts all day",
    how_to_use: "Mist generously over body after moisturizing for long-lasting fragrance.",
    ingredients: "Jasmine Absolute, Rose Extract, Hyaluronic Acid",
    skin_types: ["Dry", "Normal", "Sensitive", "Oily", "Combination"],
    skin_concerns: ["Hydration"],
    ai_tags: ["body mist", "floral", "jasmine", "rose", "laneige"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 680,
  },
  {
    id: "p65",
    name: "Kundal Honey & Macadamia Hair Perfume — White Musk",
    brand_id: "b13",
    origin: "Thailand",
    category_id: "c11",
    price: 14,
    original_price: 18,
    stock: 28,
    slug: "kundal-honey-hair-perfume-white-musk",
    description: "Leave-in hair perfume mist with white musk and honey. Adds a light, lingering scent while taming flyaways.",
    main_benefit: "Hair fragrance and flyaway control",
    how_to_use: "Spray lightly from 20cm onto dry hair. Do not rinse.",
    ingredients: "Honey Extract, White Musk, Argan Oil, Silk Amino Acid",
    skin_types: ["Dry", "Normal", "Combination"],
    skin_concerns: ["Dryness"],
    ai_tags: ["hair perfume", "white musk", "flyaway", "kundal"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 870,
  },
  {
    id: "p66",
    name: "Beauty of Joseon Hanbang Fragrance Mist",
    brand_id: "b3",
    origin: "Cambodia",
    category_id: "c11",
    price: 28,
    stock: 10,
    slug: "beauty-of-joseon-hanbang-fragrance-mist",
    description: "An elegant Korean herbal-inspired mist with a warm sandalwood and ginseng base. Uniquely calming.",
    main_benefit: "Sophisticated herbal fragrance",
    how_to_use: "Spray onto clothes and wrists. Can be layered over the Joseon body care line.",
    ingredients: "Ginseng Root Extract, Sandalwood, Hwanggi, Rice Bran Water",
    skin_types: ["Oily", "Dry", "Sensitive", "Combination", "Normal"],
    skin_concerns: ["Dull Skin", "Brightening"],
    ai_tags: ["fragrance", "herbal", "ginseng", "k-beauty scent"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 520,
  },

  // ── BODY CARE — c12 ──────────────────────────────────────────────────────────

  {
    id: "p67",
    name: "CeraVe Moisturizing Lotion for Dry to Very Dry Skin",
    brand_id: "b5",
    origin: "USA",
    category_id: "c12",
    price: 16,
    original_price: 20,
    stock: 28,
    slug: "cerave-moisturizing-lotion-dry-skin",
    description: "Lightweight daily body lotion with ceramides and hyaluronic acid for 24-hour moisture without greasiness.",
    main_benefit: "24-hour hydration for dry body skin",
    how_to_use: "Apply to body once or twice daily after showering while skin is still slightly damp.",
    ingredients: "Ceramides NP, AP, EOP, Hyaluronic Acid, Niacinamide",
    skin_types: ["Dry", "Sensitive", "Normal"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["body lotion", "ceramide", "dry skin", "cerave body"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 4200,
  },
  {
    id: "p68",
    name: "Laneige Cream Skin Body Milk",
    brand_id: "b9",
    origin: "Cambodia",
    category_id: "c12",
    price: 28,
    stock: 12,
    slug: "laneige-cream-skin-body-milk",
    description: "A milky body lotion that floods skin with moisture and leaves an all-day dewy, glass-skin effect.",
    main_benefit: "Glass-skin glow for the body",
    how_to_use: "Apply generously after bathing. Massage in circular motions until absorbed.",
    ingredients: "White Tea Water, Hyaluronic Acid, Glycerin",
    skin_types: ["Dry", "Normal", "Combination", "Sensitive"],
    skin_concerns: ["Hydration", "Dryness", "Dull Skin"],
    ai_tags: ["body milk", "glass skin", "dewy", "laneige body"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 1880,
  },
  {
    id: "p69",
    name: "La Roche-Posay Lipikar Balm AP+ Intense",
    brand_id: "b8",
    origin: "France",
    category_id: "c12",
    price: 24,
    stock: 16,
    slug: "la-roche-posay-lipikar-balm-ap-plus",
    description: "Rich body balm for eczema-prone and very dry skin. Relieves tightness and protects the skin barrier.",
    main_benefit: "Relief for very dry and eczema-prone skin",
    how_to_use: "Apply twice daily to dry areas. For atopic skin, use immediately after bathing.",
    ingredients: "Niacinamide, Shea Butter, Thermal Water, Allantoin",
    skin_types: ["Dry", "Sensitive"],
    skin_concerns: ["Dryness", "Redness", "Hydration"],
    ai_tags: ["eczema", "body balm", "barrier", "sensitive skin body"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 3500,
  },
  {
    id: "p70",
    name: "The Ordinary Natural Moisturizing Factors — Body",
    brand_id: "b6",
    origin: "USA",
    category_id: "c12",
    price: 12,
    original_price: 15,
    stock: 20,
    slug: "the-ordinary-natural-moisturizing-factors-body",
    description: "Budget-friendly body moisturizer with NMF complex that replenishes the skin's natural hydration factors.",
    main_benefit: "Essential hydration for all skin types",
    how_to_use: "Apply to clean dry body skin as needed. Excellent as a base for other actives.",
    ingredients: "Amino Acids, PCA, Lactic Acid, Urea, Hyaluronic Acid",
    skin_types: ["Dry", "Oily", "Combination", "Normal", "Sensitive"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["body moisturizer", "nmf", "affordable", "everyday"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 2100,
  },
  {
    id: "p71",
    name: "Innisfree Green Tea Seed Serum Body Lotion",
    brand_id: "b12",
    origin: "Korea",
    category_id: "c12",
    price: 22,
    stock: 14,
    slug: "innisfree-green-tea-seed-body-lotion",
    description: "Antioxidant-rich body lotion with Jeju green tea seed extract for soft, plump, and bright skin.",
    main_benefit: "Antioxidant protection and hydration",
    how_to_use: "Apply after showering. Pat excess water first for faster absorption.",
    ingredients: "Green Tea Seed Extract, Hyaluronic Acid, Green Tea Leaf Water",
    skin_types: ["Dry", "Normal", "Combination"],
    skin_concerns: ["Hydration", "Dull Skin", "Brightening"],
    ai_tags: ["green tea body", "antioxidant", "hydrating lotion", "innisfree"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.4,
    review_count: 760,
  },
  {
    id: "p72",
    name: "Kundal Honey & Macadamia Body Wash — Baby Powder",
    brand_id: "b13",
    origin: "Korea",
    category_id: "c12",
    price: 14,
    original_price: 18,
    stock: 30,
    slug: "kundal-honey-body-wash-baby-powder",
    description: "Creamy body wash with honey and macadamia that gently cleanses without stripping, leaving skin velvety soft.",
    main_benefit: "Soft cleansing with a comforting baby powder scent",
    how_to_use: "Lather onto wet body, massage well, then rinse. Safe for daily use.",
    ingredients: "Honey Extract, Macadamia Seed Oil, Plant Surfactants, Glycerin",
    skin_types: ["Dry", "Sensitive", "Normal", "Combination"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["body wash", "honey", "baby powder", "creamy", "kundal body"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 2650,
  },
  {
    id: "p73",
    name: "Some By Mi AHA BHA PHA Body Wash",
    brand_id: "b7",
    origin: "Korea",
    category_id: "c12",
    price: 16,
    original_price: 20,
    stock: 18,
    slug: "some-by-mi-aha-bha-pha-body-wash",
    description: "Mild exfoliating body wash that targets body acne, rough patches, and uneven skin tone from neck to toe.",
    main_benefit: "Smoother, clearer body skin",
    how_to_use: "Apply to wet skin, lather, focus on problem areas, rinse. Use 3–4x weekly.",
    ingredients: "AHA, BHA, PHA, Tea Tree Oil, Aloe Vera",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Acne", "Large Pores", "Dull Skin"],
    ai_tags: ["exfoliating body wash", "body acne", "aha bha", "smooth skin"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 1340,
  },
  {
    id: "p74",
    name: "CeraVe SA Body Wash with Salicylic Acid",
    brand_id: "b5",
    origin: "USA",
    category_id: "c12",
    price: 18,
    stock: 20,
    slug: "cerave-sa-body-wash-salicylic-acid",
    description: "Exfoliating body wash with salicylic acid and ceramides. Targets KP, dry bumps, and rough texture.",
    main_benefit: "Smoother skin and keratosis pilaris relief",
    how_to_use: "Apply to wet body, lather, and rinse. Focus on arms, legs, and back. Daily use.",
    ingredients: "Salicylic Acid 2%, Ceramides, Niacinamide, Hyaluronic Acid",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Acne", "Large Pores", "Dull Skin"],
    ai_tags: ["body wash", "salicylic acid", "keratosis pilaris", "cerave body"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 3890,
  },
  {
    id: "p75",
    name: "La Roche-Posay Lipikar Syndet AP+ Body Wash",
    brand_id: "b8",
    origin: "France",
    category_id: "c12",
    price: 22,
    stock: 14,
    slug: "la-roche-posay-lipikar-syndet-body-wash",
    description: "Gentle syndet bar alternative that cleanses sensitive and eczema-prone skin without disrupting the microbiome.",
    main_benefit: "Ultra-gentle cleansing for reactive skin",
    how_to_use: "Apply to wet skin. Rinse well. Follow immediately with Lipikar body care.",
    ingredients: "La Roche-Posay Thermal Water, Shea Butter, Niacinamide",
    skin_types: ["Dry", "Sensitive"],
    skin_concerns: ["Dryness", "Redness", "Hydration"],
    ai_tags: ["sensitive body wash", "eczema", "syndet", "la roche-posay"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 1020,
  },
  {
    id: "p76",
    name: "Innisfree Jeju Volcanic Pore Scrub",
    brand_id: "b12",
    origin: "Korea",
    category_id: "c12",
    price: 19,
    original_price: 25,
    stock: 16,
    slug: "innisfree-jeju-volcanic-pore-scrub",
    description: "Gritty-but-gentle body scrub with Jeju volcanic ash. Unclogs pores and polishes dry, rough skin.",
    main_benefit: "Pore-clearing body exfoliation",
    how_to_use: "Massage onto damp skin in circular motions. Rinse thoroughly. Use 2x weekly.",
    ingredients: "Volcanic Ash, Jeju Mineral Water, Walnut Shell Powder, Kaolin",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Large Pores", "Oil Control", "Dull Skin"],
    ai_tags: ["body scrub", "volcanic", "exfoliation", "pores"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 930,
  },
  {
    id: "p77",
    name: "Kundal Honey & Macadamia Body Oil",
    brand_id: "b13",
    origin: "Korea",
    category_id: "c12",
    price: 18,
    stock: 16,
    slug: "kundal-honey-macadamia-body-oil",
    description: "Dry body oil with honey and macadamia. Absorbs quickly, leaves a satin sheen, no sticky residue.",
    main_benefit: "Lightweight body glow without greasiness",
    how_to_use: "Apply 4–5 drops to damp skin after shower. Massage until fully absorbed.",
    ingredients: "Macadamia Seed Oil, Honey Extract, Jojoba Seed Oil, Vitamin E",
    skin_types: ["Dry", "Normal", "Sensitive"],
    skin_concerns: ["Dryness", "Hydration"],
    ai_tags: ["body oil", "satin", "glow", "honey", "kundal"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 640,
  },
  {
    id: "p78",
    name: "Beauty of Joseon Glow Body Serum",
    brand_id: "b3",
    origin: "Korea",
    category_id: "c12",
    price: 24,
    stock: 12,
    slug: "beauty-of-joseon-glow-body-serum",
    description: "Lightweight body serum with rice water and niacinamide that brightens dark spots and evens body skin tone.",
    main_benefit: "Brighter, more even body skin tone",
    how_to_use: "After body wash, apply to damp skin. Pat until absorbed. Follow with lotion if needed.",
    ingredients: "Rice Bran Water, Niacinamide, Adenosine, Hwanggi Root Extract",
    skin_types: ["Oily", "Dry", "Normal", "Combination", "Sensitive"],
    skin_concerns: ["Dark Spots", "Dull Skin", "Brightening"],
    ai_tags: ["body serum", "brightening", "rice", "niacinamide body"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 850,
  },

  // ── EXTRA SKINCARE (fills new arrivals + offers + brands) ────────────────────

  {
    id: "p79",
    name: "COSRX Master Patch Intensive",
    brand_id: "b2",
    origin: "Korea",
    category_id: "c6",
    price: 8,
    original_price: 10,
    stock: 45,
    slug: "cosrx-master-patch-intensive",
    description: "XL hydrocolloid patches that absorb pus overnight and flatten blemishes by morning. No active needed.",
    main_benefit: "Overnight blemish flattening",
    how_to_use: "Apply to a clean blemish before bed. Peel off in the morning.",
    ingredients: "Hydrocolloid, Salicylic Acid 0.5%, Tea Tree Oil",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Acne", "Large Pores"],
    ai_tags: ["pimple patch", "acne", "hydrocolloid", "cosrx"],
    is_best_seller: true,
    is_hot_sale: true,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.9,
    review_count: 7800,
  },
  {
    id: "p80",
    name: "Skin1004 Hyalu-Cica Blue Serum",
    brand_id: "b4",
    origin: "Korea",
    category_id: "c3",
    price: 23,
    stock: 10,
    slug: "skin1004-hyalu-cica-blue-serum",
    description: "Cooling blue serum with hyaluronic acid and centella for immediate soothing and long-lasting hydration.",
    main_benefit: "Instant soothing and deep hydration",
    how_to_use: "Apply after cleansing and toner. Can be layered with other serums.",
    ingredients: "Centella Asiatica Extract, 5-CICA Complex, Hyaluronic Acid",
    skin_types: ["Sensitive", "Dry", "Combination"],
    skin_concerns: ["Redness", "Hydration", "Acne"],
    ai_tags: ["centella", "hyaluronic acid", "blue serum", "soothing"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.5,
    review_count: 720,
  },
  {
    id: "p81",
    name: "Anua Heartleaf Pore Control Cleansing Oil",
    brand_id: "b1",
    origin: "Korea",
    category_id: "c1",
    price: 21,
    stock: 13,
    slug: "anua-heartleaf-pore-control-cleansing-oil",
    description: "Heartleaf-infused cleansing oil that dissolves sunscreen, makeup, and sebum while calming inflamed pores.",
    main_benefit: "Deep pore cleanse with soothing heartleaf",
    how_to_use: "Apply to dry skin. Massage to emulsify, then rinse. Follow with gel cleanser.",
    ingredients: "Houttuynia Cordata Extract 55%, Squalane, Meadowfoam Seed Oil",
    skin_types: ["Oily", "Combination", "Sensitive"],
    skin_concerns: ["Acne", "Large Pores", "Oil Control"],
    ai_tags: ["cleansing oil", "heartleaf", "pore control", "double cleanse"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 2140,
  },
  {
    id: "p82",
    name: "Dr. Jart+ Focuspot Blemish Micro Tip Patch",
    brand_id: "b11",
    origin: "Korea",
    category_id: "c6",
    price: 22,
    original_price: 28,
    stock: 8,
    slug: "dr-jart-focuspot-blemish-micro-tip-patch",
    description: "Micro-tip patches that dissolve actives deep into the blemish for faster healing than standard patches.",
    main_benefit: "Faster blemish healing with microneedle delivery",
    how_to_use: "Clean and dry the area. Press patch firmly for 5 seconds. Leave on for 2 hours.",
    ingredients: "Salicylic Acid, Niacinamide, BHA, Hyaluronic Acid (via micro-tips)",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Acne"],
    ai_tags: ["micro tip", "acne patch", "blemish", "dr jart"],
    is_best_seller: false,
    is_hot_sale: true,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.6,
    review_count: 1560,
  },
  {
    id: "p83",
    name: "Beauty of Joseon Revive Serum: Rice + Probiotics",
    brand_id: "b3",
    origin: "Korea",
    category_id: "c3",
    price: 24,
    stock: 11,
    slug: "beauty-of-joseon-revive-serum-rice-probiotics",
    description: "Brightening serum with fermented rice water and probiotics that softens skin texture and adds luminosity.",
    main_benefit: "Radiant skin texture through fermentation",
    how_to_use: "Apply 2–3 drops to clean skin before moisturizer. Can be mixed into moisturizer.",
    ingredients: "Rice Bran Water, Lactobacillus Ferment, Niacinamide, Adenosine",
    skin_types: ["Dry", "Combination", "Normal", "Sensitive"],
    skin_concerns: ["Brightening", "Dull Skin", "Dark Spots"],
    ai_tags: ["rice serum", "probiotic", "brightening", "k-beauty"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 1820,
  },
  {
    id: "p84",
    name: "Torriden Balanceful Cica Toner",
    brand_id: "b15",
    origin: "Korea",
    category_id: "c2",
    price: 19,
    stock: 14,
    slug: "torriden-balanceful-cica-toner",
    description: "Soothing cica toner that balances pH, soothes redness, and prepares skin for serums and moisturizers.",
    main_benefit: "Barrier balancing and redness reduction",
    how_to_use: "Sweep across face with cotton pad or hands after cleansing.",
    ingredients: "Centella Asiatica Extract, Madecassoside, Panthenol, Allantoin",
    skin_types: ["Sensitive", "Combination", "Dry", "Normal"],
    skin_concerns: ["Redness", "Acne", "Hydration"],
    ai_tags: ["cica toner", "centella", "soothing", "torriden"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.7,
    review_count: 1150,
  },
  {
    id: "p85",
    name: "Some By Mi Retinol Intense Reactivating Toner",
    brand_id: "b7",
    origin: "Korea",
    category_id: "c2",
    price: 22,
    stock: 9,
    slug: "some-by-mi-retinol-intense-toner",
    description: "Retinol-infused toner that primes skin for actives, refines pores, and supports gentle overnight renewal.",
    main_benefit: "Retinol-primed smooth skin",
    how_to_use: "Use PM only after cleansing. Avoid sun exposure. Follow with serum.",
    ingredients: "Retinol, Retinal, Panthenol, BHA, Squalane",
    skin_types: ["Oily", "Combination", "Normal"],
    skin_concerns: ["Large Pores", "Dull Skin", "Acne"],
    ai_tags: ["retinol toner", "pores", "overnight", "some by mi"],
    is_best_seller: false,
    is_hot_sale: false,
    is_new_arrival: true,
    is_ai_recommendable: true,
    rating: 4.4,
    review_count: 640,
  },
  {
    id: "p86",
    name: "COSRX Propolis Light Ampule",
    brand_id: "b2",
    origin: "Korea",
    category_id: "c3",
    price: 32,
    stock: 10,
    slug: "cosrx-propolis-light-ampule",
    description: "83% black bee propolis ampule that visibly plumps, calms, and perfects skin with long-term use.",
    main_benefit: "Calming and plumping propolis treatment",
    how_to_use: "Apply 3–4 drops after toner. Pat into skin. Use AM and PM.",
    ingredients: "Black Bee Propolis Extract 83%, Niacinamide, Panthenol",
    skin_types: ["Oily", "Dry", "Combination", "Normal", "Sensitive"],
    skin_concerns: ["Acne", "Brightening", "Hydration"],
    ai_tags: ["propolis", "ampule", "plumping", "cosrx"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 2890,
  },
  {
    id: "p87",
    name: "La Roche-Posay Effaclar Duo+",
    brand_id: "b8",
    origin: "France",
    category_id: "c6",
    price: 35,
    stock: 9,
    slug: "la-roche-posay-effaclar-duo-plus",
    description: "Dermatologist-recommended acne moisturizer with LHA and niacinamide. Reduces breakouts and post-acne marks.",
    main_benefit: "Acne treatment and mark reduction",
    how_to_use: "Apply as a moisturizer on clean skin. Use AM and/or PM.",
    ingredients: "LHA, Niacinamide, Thermal Water, Micro-Exfoliant",
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Acne", "Large Pores", "Dark Spots"],
    ai_tags: ["effaclar", "acne treatment", "lha", "dermatologist"],
    is_best_seller: true,
    is_hot_sale: false,
    is_new_arrival: false,
    is_ai_recommendable: true,
    rating: 4.8,
    review_count: 5600,
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cu1",
    name: "Sreyka Chan",
    phone: "012345678",
    telegram_username: "@sreyka",
    address: "St 278, Phnom Penh",
    created_at: "2026-05-20T00:00:00Z",
  },
  {
    id: "cu2",
    name: "Ratha Dara",
    phone: "098765432",
    telegram_username: "@ratha",
    address: "St 51, Phnom Penh",
    created_at: "2026-05-25T00:00:00Z",
  },
  {
    id: "cu3",
    name: "Bopha Sok",
    phone: "077123456",
    address: "Siem Reap Province",
    created_at: "2026-05-27T00:00:00Z",
  },
  {
    id: "cu4",
    name: "Malis Vann",
    phone: "070882211",
    telegram_username: "@malisglow",
    address: "BKK1, Phnom Penh",
    created_at: "2026-05-30T00:00:00Z",
  },
  {
    id: "cu5",
    name: "Nita Long",
    phone: "0964567890",
    telegram_username: "@nitalong",
    address: "Toul Kork, Phnom Penh",
    created_at: "2026-05-31T00:00:00Z",
  },
  {
    id: "cu6",
    name: "Vireak Lim",
    phone: "089345111",
    address: "Battambang Province",
    created_at: "2026-06-01T00:00:00Z",
  },
];

export type OrderWithItems = Order & { items: OrderItem[] };

export const MOCK_ORDERS: OrderWithItems[] = [
  {
    id: "o1",
    order_code: "ORD-1001",
    customer_id: "cu1",
    customer_name: "Sreyka Chan",
    customer_phone: "012345678",
    customer_telegram: "@sreyka",
    delivery_address: "St 278, Phnom Penh",
    delivery_option: "Delivery in Phnom Penh",
    note: "Please pack carefully.",
    total_amount: 36,
    order_status: "Delivering",
    payment_status: "Payment Successful",
    delivery_status: "Delivering",
    created_at: "2026-05-28T08:00:00Z",
    items: [
      {
        id: "oi1",
        order_id: "o1",
        product_id: "p1",
        product_name: "Anua Heartleaf 77% Soothing Toner",
        quantity: 2,
        unit_price: 18,
        total_price: 36,
      },
    ],
  },
  {
    id: "o2",
    order_code: "ORD-1002",
    customer_id: "cu2",
    customer_name: "Ratha Dara",
    customer_phone: "098765432",
    customer_telegram: "@ratha",
    delivery_address: "St 51, Phnom Penh",
    delivery_option: "Delivery in Phnom Penh",
    total_amount: 29,
    order_status: "New Order",
    payment_status: "Payment Pending",
    delivery_status: "Order Created",
    created_at: "2026-05-29T06:30:00Z",
    items: [
      {
        id: "oi2",
        order_id: "o2",
        product_id: "p2",
        product_name: "COSRX Low pH Good Morning Gel Cleanser",
        quantity: 1,
        unit_price: 12,
        total_price: 12,
      },
      {
        id: "oi3",
        order_id: "o2",
        product_id: "p3",
        product_name: "Beauty of Joseon Relief Sun SPF50+",
        quantity: 1,
        unit_price: 17,
        total_price: 17,
      },
    ],
  },
  {
    id: "o3",
    order_code: "ORD-1003",
    customer_id: "cu3",
    customer_name: "Bopha Sok",
    customer_phone: "077123456",
    delivery_address: "Siem Reap Province",
    delivery_option: "Delivery to province",
    total_amount: 16,
    order_status: "Completed",
    payment_status: "Payment Successful",
    delivery_status: "Completed",
    created_at: "2026-05-27T14:00:00Z",
    items: [
      {
        id: "oi4",
        order_id: "o3",
        product_id: "p6",
        product_name: "CeraVe Moisturizing Cream",
        quantity: 1,
        unit_price: 16,
        total_price: 16,
      },
    ],
  },
  {
    id: "o4",
    order_code: "ORD-1004",
    customer_id: "cu4",
    customer_name: "Malis Vann",
    customer_phone: "070882211",
    customer_telegram: "@malisglow",
    delivery_address: "BKK1, Phnom Penh",
    delivery_option: "Delivery in Phnom Penh",
    note: "Please deliver after 6 PM.",
    total_amount: 69,
    order_status: "Packing",
    payment_status: "Payment Submitted",
    delivery_status: "Packing",
    created_at: "2026-05-30T10:15:00Z",
    items: [
      {
        id: "oi5",
        order_id: "o4",
        product_id: "p15",
        product_name: "Torriden Dive-In Low Molecular Hyaluronic Acid Serum",
        quantity: 1,
        unit_price: 21,
        total_price: 21,
      },
      {
        id: "oi6",
        order_id: "o4",
        product_id: "p25",
        product_name: "Skin1004 Hyalu-Cica Water-Fit Sun Serum SPF50+",
        quantity: 2,
        unit_price: 18,
        total_price: 36,
      },
      {
        id: "oi7",
        order_id: "o4",
        product_id: "p12",
        product_name: "Rom&nd Juicy Lasting Tint — Figfig",
        quantity: 1,
        unit_price: 11,
        total_price: 11,
      },
    ],
  },
  {
    id: "o5",
    order_code: "ORD-1005",
    customer_id: "cu5",
    customer_name: "Nita Long",
    customer_phone: "0964567890",
    customer_telegram: "@nitalong",
    delivery_address: "Toul Kork, Phnom Penh",
    delivery_option: "Delivery in Phnom Penh",
    total_amount: 119,
    order_status: "Preparing",
    payment_status: "Payment Successful",
    delivery_status: "Preparing",
    created_at: "2026-05-31T09:45:00Z",
    items: [
      {
        id: "oi8",
        order_id: "o5",
        product_id: "p20",
        product_name: "Maison Margiela Replica Lazy Sunday Morning EDT",
        quantity: 1,
        unit_price: 85,
        total_price: 85,
      },
      {
        id: "oi9",
        order_id: "o5",
        product_id: "p28",
        product_name: "Laneige Water Sleeping Mask",
        quantity: 1,
        unit_price: 32,
        total_price: 32,
      },
    ],
  },
  {
    id: "o6",
    order_code: "ORD-1006",
    customer_id: "cu6",
    customer_name: "Vireak Lim",
    customer_phone: "089345111",
    delivery_address: "Battambang Province",
    delivery_option: "Delivery to province",
    note: "Call before delivery.",
    total_amount: 49,
    order_status: "Waiting Payment",
    payment_status: "Payment Pending",
    delivery_status: "Order Created",
    created_at: "2026-06-01T01:20:00Z",
    items: [
      {
        id: "oi10",
        order_id: "o6",
        product_id: "p18",
        product_name: "Kundal Honey & Macadamia Shampoo — Baby Powder",
        quantity: 1,
        unit_price: 15,
        total_price: 15,
      },
      {
        id: "oi11",
        order_id: "o6",
        product_id: "p19",
        product_name: "Kundal Protein Treatment — White Musk",
        quantity: 1,
        unit_price: 16,
        total_price: 16,
      },
      {
        id: "oi12",
        order_id: "o6",
        product_id: "p31",
        product_name: "Lumière Soft Cloud Body Cream",
        quantity: 1,
        unit_price: 18,
        total_price: 18,
      },
    ],
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "pay1",
    order_id: "o1",
    payment_method: "ABA",
    amount: 36,
    payment_status: "Payment Successful",
    paid_at: "2026-05-28T09:00:00Z",
  },
  {
    id: "pay2",
    order_id: "o2",
    payment_method: "Manual",
    amount: 29,
    payment_status: "Payment Pending",
  },
  {
    id: "pay3",
    order_id: "o3",
    payment_method: "ABA",
    amount: 16,
    payment_status: "Payment Successful",
    paid_at: "2026-05-27T15:00:00Z",
  },
  {
    id: "pay4",
    order_id: "o4",
    payment_method: "Bakong",
    amount: 69,
    payment_status: "Payment Submitted",
    payment_reference: "BKG-884201",
  },
  {
    id: "pay5",
    order_id: "o5",
    payment_method: "ABA",
    amount: 119,
    payment_status: "Payment Successful",
    transaction_id: "ABA-20260531-501",
    paid_at: "2026-05-31T10:00:00Z",
  },
  {
    id: "pay6",
    order_id: "o6",
    payment_method: "Cash on Delivery",
    amount: 49,
    payment_status: "Payment Pending",
  },
];

export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: "del1",
    order_id: "o1",
    delivery_company: "Lalamove",
    tracking_code: "LL2026001",
    rider_name: "Dara Sok",
    rider_phone: "011234567",
    delivery_note: "Handle with care",
    estimated_delivery_date: "2026-05-29",
    delivery_status: "Delivering",
  },
  {
    id: "del2",
    order_id: "o2",
    delivery_status: "Order Created",
  },
  {
    id: "del3",
    order_id: "o3",
    delivery_company: "Cambodia Post",
    tracking_code: "CP2026003",
    delivery_note: "Delivered successfully",
    delivery_status: "Completed",
  },
  {
    id: "del4",
    order_id: "o4",
    delivery_company: "GrabExpress",
    tracking_code: "GR2026004",
    rider_name: "Sopheak",
    rider_phone: "092441122",
    delivery_note: "Rider will pick up after packing.",
    estimated_delivery_date: "2026-05-30",
    delivery_status: "Packing",
  },
  {
    id: "del5",
    order_id: "o5",
    delivery_company: "Lalamove",
    tracking_code: "LL2026005",
    rider_name: "Chanthy",
    rider_phone: "010889900",
    estimated_delivery_date: "2026-05-31",
    delivery_status: "Preparing",
  },
  {
    id: "del6",
    order_id: "o6",
    delivery_company: "Virak Buntham",
    tracking_code: "VBT2026006",
    delivery_note: "Province delivery starts after payment confirmation.",
    estimated_delivery_date: "2026-06-03",
    delivery_status: "Order Created",
  },
];
